### ISSUE TITLE
Task #1 Add proper build instructions

### ISSUE THREAD

**Issue by manosbatsis** [manosbatsis/restdude#2]
I cleaned up the commuted files i.e.:

- kept  the marionette based project and removed the other two
- moved it to the restdude-marionette folder as previously discussed

Your first task is to add proper build instructions to the project, as plain text in this file:
 
[/restdude-marionette/README.md](https://github.com/manosbatsis/restdude/blob/master/restdude-marionette/README.md)

as the text applies to the react-based project, not the marionette one. Please use git properly from now on from your editor, IDE or command line. No browser uploading and no committing files outside the folders you are working in like the README.txt i removed from the root folder earlier.

**Comment by manosbatsis** [comment]
I see the updated README instructions still refer to the wrong react-based project/generator?

**Comment by nkapetanas** [comment]
The README instructions refer to the project I uploaded and you moved in restdude/restdude-marionette/.
I cloned the project and I run all the necessary things(referred to README)  in order the generator to work. I am little confused.. There is and another project in restdude? The project that I uploaded is generator-react-require that can be used to create a simple todo application using React/JSX, requireJS, Socket.IO, Express, Jasmine, Sass, Bootstrap, JSHint and JSCS. Please comment in order to get clear the project you are refereeing and do it properly.

**Comment by manosbatsis** [comment]
Some issues with the README:

1. Are all items in "Prerequisites" really required and why? Basically i cant figure out why yo and compass are neded and why we need gem modules
3. I tried to follow the instructions to run the project but i'm stuck at step "4. Run Grunt with: grunt ". The error i get is:

```
manos@sobol:~/git/restdude/restdude-marionette$ grunt
Running "prod" task
Warning: Cannot read property 'options' of undefined Use --force to continue.

Aborted due to warnings.
```

**Comment by nkapetanas** [comment]
1. All prerequisites are not required but is good to keep them installed in order to make changes easier if we want( yo and compass). Also we need gem modules in order to install Sass ( and also Compass if we need it). Please comment if you want to delete those steps( yo and compass).
2. The error you are getting is because I am trying to make the adjustments you asked me on tasks 2 & 3 and for this reason there are some bugs to be fixed in order to run smooth. I am trying to solve them.

**Comment by nkapetanas** [comment]
README file is updated with right build and run steps and better documentation.
