### ISSUE TITLE
Task #2: Add Core-UI Sass

### ISSUE THREAD

**Issue by manosbatsis** [manosbatsis/restdude#3]
Update the Gruntfile.js etc. to use CoreUI and S**a**ss  (see http://coreui.io/) instead of  bootstrap and the older Scss system

**Comment by nkapetanas** [comment]
Please check the Gruntfile.js , the requirejs and sass section, in order to connect them with the right folders(in order to take the data). Also try to run the project with 1) grunt to build it , 2) grunt back-end to start the server and 3) grunt front-end to see the main page on localhost:9000.

**Comment by manosbatsis** [comment]
Could you please explain "in order to connect them with the right folders"? Please provide file/line numbers or examples of what we need to do.

Finally I was able to browse the home page and see CoreUI but had to use grunt backent/frontend without the dashes ("-"). Also these instructions seem missing from the README and I could not launch the app with just the info written in there.

**Comment by nkapetanas** [comment]
Take a look at the Gruntfile.js , line 124-147 (requirejs) and line 150-160 (sass). I would like to know what files you want to put for the requirejs and the path in order to complete the path in the code. Same for Sass. If I am mistaken please comment and correct me in order to get the logic part right.

I updated the README file. I couldn't understand the part about the dashes. What other parameter you want to pass? Also it works without the dashes.

**Comment by manosbatsis** [comment]
i think you just need to try with app/main.js etc.

**Comment by manosbatsis** [comment]
as for the sass i really havent looked at how you have implemented sass-ing bootstrap and/or coreUI so you are probably the best in figuring out how that should be build and how a developer can customize with sass variables etc.

**Comment by nkapetanas** [comment]
I have updated the documentation( README file) about sass, sass customization and core-ui. Please check it and comment for errors.
